# Generated by Django 4.2.3 on 2023-07-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(default='Nodes Name', max_length=100),
        ),
    ]
