# Generated by Django 4.2.3 on 2023-07-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_index_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='index',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
