# Generated by Django 4.2.3 on 2023-07-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_index_email_alter_index_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='username',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
