# Generated by Django 3.2.20 on 2023-07-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_index_email_alter_index_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='student',
        ),
    ]
