# Generated by Django 3.2.20 on 2023-07-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_index_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
    ]
